const categories = {
  adventure: {
    label: "Adventure",
    slug: "adventure",
    cities: ["kumbhalgarh", "sam"],
  },
  backpacker: {
    label: "Backpacker",
    slug: "backpacker",
    cities: ["goa"],
  },
  coastal: {
    label: "Coastal",
    slug: "coastal",
    cities: ["somnath", "dwarka", "mumbai", "goa"],
  },
  desert: {
    label: "Desert",
    slug: "desert",
    cities: ["bikaner", "sam", "jaisalmer"],
  },
  ease_of_work: {
    label: "Ease Of Work",
    slug: "ease-of-work",
    cities: ["pune", "mumbai"],
  },
  heritage: {
    label: "Heritage",
    slug: "heritage",
    cities: [
      "jaipur",
      "chittorgarh",
      "udaipur",
      "kumbhalgarh",
      "ahemdabad",
      "kevadiya",
      "vadodara",
      "bikaner",
      "jaisalmer",
      "jodhpur",
      "ahmedabad-gandhinagar",
      "sambhajinagar",
      "pune",
      "goa",
      "gwalior",
      "bhopal",
      "orchha",
      "jhansi",
      "khajurao",
    ],
  },
  metro: {
    label: "Metro",
    slug: "metro",
    cities: [
      "jaipur",
      "ahemdabad",
      "surat",
      "rajkot",
      "ahmedabad-gandhinagar",
      "indore",
      "pune",
      "mumbai",
      "nagpur",
      "bhopal",
    ],
  },
  pilgrimage: {
    label: "Pilgrimage",
    slug: "pilgrimage",
    cities: ["somnath", "dwarka", "ajmer-pushkar", "omkareshwar", "nashik", "shirdi"],
  },
};

export default categories;
